### ISSUE TITLE
Gmail api throws this error if api option not enabled and does not sent email  

### ISSUE THREAD

**Issue by abusohib** [arafatrahman/free-wp-smtp-plugin#1]
Fatal error: Uncaught Google_Service_Exception: { "error": { "code": 403, "message": "Gmail API has not been used in project 981231720285 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/gmail.googleapis.com/overview?project=981231720285 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "errors": [ { "message": "Gmail API has not been used in project 981231720285 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/gmail.googleapis.com/overview?project=981231720285 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "domain": "usageLimits", "reason": "accessNotConfigured", "extendedHelp": "https://console.developers.google.com" } ], "status": "PERMISSION_DENIED" } } in /var/www/localdev.approveme.me/wp-content/plugins/Free-WP-SMTP in /var/www/localdev.approveme.me/wp-content/plugins/Free-WP-SMTP-Plugin/vendor/google/apiclient/src/Google/Http/REST.php on line 123

After enabling it fix the issue . 
https://console.developers.google.com/apis/api/gmail.googleapis.com/overview?project=981231720285

http://kauniaweb.com/i/HSK4

**Comment by webbirduk** [comment]
it's fixed now
